protein_model_path: "/home/longyh/software/prot_bert/"
mol_config_path: "./Data/mol/hparams.yaml"
mol_ckpt_path: "/home/longyh/database/molformer/PretrainedMoLFormer/checkpoints/N-Step-Checkpoint_3_30000.ckpt"
mol_vocab_path: "./Data/mol/bert_vocab.txt"
csv_file: "/work/longyh/MolProtMHC/Data/test1k.csv"
protein_col: "combine"
smiles_col: "canonical_smiles"
label_col: "binding300"
batch_size: 32
input_dim: 1792
hidden_dim: 512
output_dim: 1
learning_rate: 1e-4
num_epochs: 10
model_save_path: "./train_output/model.pth"
log_file: "./train_output/training.log"